web/scalica/micro/urls.py
from django.conf.urls import include, url

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^stream/(?P<user_id>[0-9]+)/$', views.stream, name='stream'),
    url(r'^post/$', views.post, name='post'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^register/$', views.register, name='register'),
    url('^', include('django.contrib.auth.urls'))
]

web/scalica/scalica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^micro/', include('micro.urls', namespace="micro")),
    url(r'^admin/', include(admin.site.urls)),
]

web/scalica/micro/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models
from django.forms import ModelForm, TextInput

# Note: For now, all fields that were previously
# foreign keys to the auth User, must be named user_id.
# They CAN have ScalicaUser as a Foreign Key.
class ScalicaUser(models.Model):
  user_id = models.BigIntegerField(primary_key=True)
  username = models.CharField(max_length=30, unique=True)
  first_name = models.CharField('first name', max_length=30, blank=True)
  last_name = models.CharField('last name', max_length=30, blank=True)
  # User data that is non-auth-related can go here (e.g. avatar)

class Post(models.Model):
  user_id = models.BigIntegerField(db_index=True)
  text = models.CharField(max_length=256, default="")
  pub_date = models.DateTimeField('date_posted')
  def __str__(self):
    if len(self.text) < 16:
      desc = self.text
    else:
      desc = self.text[0:16]
    return str(self.user_id) + ':' + desc

class Following(models.Model):
  user_id = models.BigIntegerField(db_index=True)
  followee_id = models.BigIntegerField(db_index=True)
  follow_date = models.DateTimeField('follow date')
  def __str__(self):
    return std(self.user_id) + "->" + str(self.followee_id)

# Model Forms
class PostForm(ModelForm):
  class Meta:
    model = Post
    fields = ('text',)
    widgets = {
      'text': TextInput(attrs={'id' : 'input_post'}),
    }

class FollowingForm(ModelForm):
  class Meta:
    model = Following
    fields = ('followee_id',)

class MyUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm.Meta):
    help_texts = {
      'username' : '',
    }

web/scalica/micro/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone
from .models import Following, Post, ScalicaUser
from .models import FollowingForm, PostForm, MyUserCreationForm
from utils.hints import set_user_for_sharding
from routers import bucket_users_into_shards
from processor import processor


# Anonymous views
#################
def index(request):
  if request.user.is_authenticated():
    return home(request)
  else:
    return anon_home(request)

def anon_home(request):
  return render(request, 'micro/public.html')

def stream(request, user_id):  
  # See if to present a 'follow' button
  form = None
  if request.user.is_authenticated() and request.user.id != int(user_id):
    try:
      following_query = Following.objects
      set_user_for_sharding(following_query, request.user.id)
      f = following_query.get(user_id=request.user.id, followee_id=user_id)
    except Following.DoesNotExist:
      form = FollowingForm
  user_query = ScalicaUser.objects
  set_user_for_sharding(user_query, user_id)
  user = user_query.get(pk=user_id)
  post_list = Post.objects.filter(user_id=user_id).order_by('-pub_date')
  set_user_for_sharding(post_list, user_id)
  paginator = Paginator(post_list, 10)
  page = request.GET.get('page')
  try:
    posts = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    posts = paginator.page(1) 
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    posts = paginator.page(paginator.num_pages)
  context = {
    'posts' : posts,
    'stream_user' : user,
    'form' : form,
  }
  return render(request, 'micro/stream.html', context)

def register(request):
  if request.method == 'POST':
    form = MyUserCreationForm(request.POST)
    new_user = form.save(commit=True)
    # Create a mirror sharded User model.
    u = ScalicaUser(
        user_id=new_user.id, username=new_user.username, 
        first_name=new_user.first_name, last_name=new_user.last_name)
    u.save()
    # Log in that user.
    user = authenticate(username=new_user.username,
                        password=form.clean_password2())
    if user is not None:
      login(request, user)
    else:
      raise Exception
    return home(request)
  else:
    form = MyUserCreationForm
  return render(request, 'micro/register.html', {'form' : form})

# Authenticated views
#####################
@login_required
def home(request):
  '''List of recent posts by people I follow'''
  my_posts = Post.objects.filter(user_id=request.user.id).order_by('-pub_date')
  set_user_for_sharding(my_posts, request.user.id)
  if my_posts:
    my_post = my_posts[0]
  else:
    my_post = None
  following_list =  Following.objects.filter(user_id=request.user.id)
  set_user_for_sharding(following_list, request.user.id)
  follows = [o.followee_id for o in following_list]
  # We need to query every shard where there are users who this user follows
  # We break the users into shards, then for each shard we annotate it with
  # a hint for that shard, issue a query and at the end join all results.
  # Note that this is not very efficient if users are spread accorss many
  # shards. This is where Fan-out could help improve performance.
  shards_to_query = bucket_users_into_shards(follows)
  all_posts = []
  for shard, user_ids in shards_to_query.iteritems():   
    post_list = Post.objects.filter(
      user_id__in=user_ids).order_by('-pub_date')[0:10]
    set_user_for_sharding(post_list, shard)
    # The list comprehension actually invokes the db query in the QuerySet.
    all_posts = all_posts + [p for p in post_list]
  # TODO: Note that all_posts still needs to be sorted by time again, because
  # it is only ordered within each shard.
  context = {
    'post_list': all_posts,
    'my_post' : my_post,
    'post_form' : PostForm
  }
  return render(request, 'micro/home.html', context)

# Allows to post something and shows my most recent posts.
@login_required
def post(request):
  if request.method == 'POST':
    form = PostForm(request.POST)
    new_post = form.save(commit=False)
    new_post.user_id = request.user.id
    new_post.pub_date = timezone.now()
    new_post.save()
    # Make an RPC call to a backend service to process the post.
    processor.process_post(new_post.user_id, new_post.id, new_post.text)
    return home(request)
  else:
    form = PostForm
  return render(request, 'micro/post.html', {'form' : form})

@login_required
def follow(request):
  if request.method == 'POST':
    form = FollowingForm(request.POST)
    new_follow = form.save(commit=False)
    new_follow.user_id = request.user.id
    new_follow.follow_date = timezone.now()
    new_follow.save()
    return home(request)
  else:
    form = FollowingForm
  return render(request, 'micro/follow.html', {'form' : form})

web/scalica/micro/templates/micro/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'micro/style.css' %}" />
  <title>Scalica</title>
</head> 
<body>
  <div id="header">
    {% if user.is_authenticated %}
      {{ user.username }}
      <a href="{% url 'micro:logout' %}">Log Out</a>
    {% else %}
      <a href="{% url 'micro:login' %}">Log In</a>
    {% endif %}
    {% block header %}{% endblock header %}
  </div>
  <div id="sidebar">
    {% block sidebar %}{% endblock sidebar %}
  </div>
  <div id="content">
    {% block content %}{% endblock content %}
  </div>
  <div id="footer">
    <p>Copyright Scalica</p>
    {% block footer %}{% endblock footer %}
  </div>
</body>
</html>

web/scalica/micro/templates/micro/follow.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/follow/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/home.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ user.username }} <p>
{% endblock %}
{% block content %}
<div id="status">
{% if my_post %}
 {{ my_post.text }} ({{ my_post.pub_date|naturaltime }})
{% endif %}
</div>
<div id="post">
  <form action="/micro/post/" method="post">
    {% csrf_token %}
    {{ post_form.text }}
    <input type="submit" value="Post" />
  </form>
</div>
<p>
<div>
{% if post_list %}
  <table id="postlist">
    {% for post in post_list %}
      <tr>
        <td>
          <img src="{% static "micro/images/user_s.png" %}" alt="Generic User"/>
        </td>
        <td>
          {{ post.text }}
        </td>
      </tr>
      <tr>
        <td></td>
        <td>
          <a href="{% url 'micro:stream' post.user_id %}">
            {{ post.user.username }}
          </a>
          ({{ post.pub_date|naturaltime }})
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No posts are available.</p>
{% endif %}
</div>
{% endblock %}

web/scalica/micro/templates/micro/post.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/post/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/public.html
{% extends "micro/base.html" %}
{% block content %}
  <h1>Welcome to Scalica</h1></br>
  New Users: <a href="{% url 'micro:register' %}">Register</a> </br>
  Existing Users: <a href="{% url 'micro:login' %}">Log In</a>
{% endblock %}

web/scalica/micro/templates/micro/register.html
{% extends "micro/base.html" %}
{% block content %}
<form action="/micro/register/" method="post">
<table class="registerTable">
  {% csrf_token %}
  {{ form.as_table }}
</table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

web/scalica/micro/templates/micro/stream.html
{% extends "micro/base.html" %}
{% load humanize %}
{% load staticfiles %}
{% block sidebar %}
<img src="{% static "micro/images/user.png" %}" alt="Generic User"/> <br>
{{ stream_user.username }}
{% if form %}
  <form action="/micro/follow/" method="post">
    {% csrf_token %}
    <input type="hidden" id="id_followee" name="followee_id" value="{{ stream_user.user_id }}" />
    <input type="submit" value="Follow" />
  </form>
{% endif %}
{% endblock %}
{% block content %}
{% for post in posts %}
  <li>
    {{ post.text }} ({{ post.pub_date|naturaltime }})
  </li>
{% endfor %}
{# TODO: see complete pagination example in Django doc for more #}
{% endblock %}